require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses
