require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake
  - rubocop-slim

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/{bundle,dev,rails,rake,setup}'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'script/**/*'

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\s*# .+'
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
### must be together {
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
### }
Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses
